# Generated by Django 4.1.6 on 2023-02-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_orderline_sizeid_alter_orderline_productid"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="label",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Status"
            ),
        ),
    ]
