# Generated by Django 4.1.6 on 2023-02-09 21:09

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoryName",
                    models.CharField(
                        default="hoodie",
                        max_length=200,
                        verbose_name="Product Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Hoodie 1", max_length=200, verbose_name="Product Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Product Description"),
                ),
                (
                    "isFeatured",
                    models.BooleanField(
                        default=False, verbose_name="Show on home page"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                ("dateModified", models.DateTimeField(auto_now=True)),
                (
                    "productCategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="S", max_length=1, verbose_name="Size Label"
                    ),
                ),
                (
                    "sizeName",
                    models.CharField(
                        default="small", max_length=100, verbose_name="Size Title"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantityInStock",
                    models.IntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.size"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageURL",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_image_path,
                        verbose_name="Image File",
                    ),
                ),
                (
                    "altText",
                    models.CharField(
                        default="image alternative",
                        max_length=200,
                        null=True,
                        verbose_name="Image Name",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="productSizes",
            field=models.ManyToManyField(
                related_name="size", through="products.ProductSize", to="products.size"
            ),
        ),
    ]
