# Generated by Django 4.1.6 on 2023-02-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantityInStock", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="size",
            name="sizeName",
            field=models.CharField(default="small", max_length=100),
        ),
        migrations.AlterField(
            model_name="size",
            name="label",
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name="PorductSize",
        ),
        migrations.AddField(
            model_name="productsize",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.size"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productSizes",
            field=models.ManyToManyField(
                related_name="size", through="products.ProductSize", to="products.size"
            ),
        ),
    ]
