# Generated by Django 4.1.6 on 2023-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productSizes",
            field=models.ManyToManyField(
                related_name="size", through="products.ProductSize", to="products.size"
            ),
        ),
    ]
