# Generated by Django 4.1.6 on 2023-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_productcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="label",
            field=models.CharField(
                default="S", max_length=5, verbose_name="Size Label"
            ),
        ),
    ]
