# Generated by Django 4.1.6 on 2023-02-08 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productsize_size_sizename_alter_size_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productID",
            field=models.UUIDField(
                default=uuid.uuid5, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
