# Generated by Django 4.1.6 on 2023-02-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_productsizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="productSizes",
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productSizes",
                to="products.product",
            ),
        ),
    ]
