# Generated by Django 4.1.6 on 2023-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_size_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="quantitySold",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Quantity Sold"
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="quantityInStock",
            field=models.PositiveBigIntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
