# Generated by Django 4.1.6 on 2023-02-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_productid"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="altText",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
