# Generated by Django 4.1.6 on 2023-02-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimage_alttext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="quantityInStock",
            field=models.IntegerField(default=1),
        ),
    ]
