# Generated by Django 4.1.6 on 2023-02-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productsize_quantitysold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="productSizes",
        ),
    ]
