# Generated by Django 4.1.6 on 2023-02-09 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productID",
            field=models.UUIDField(
                default=uuid.UUID("fd2883ba-08ef-405c-858e-542715d74873"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
