# Generated by Django 4.1.6 on 2023-02-09 08:19

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_productid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True, verbose_name="Product Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="isFeatured",
            field=models.BooleanField(verbose_name="Show on home page"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Product Title"),
        ),
        migrations.AlterField(
            model_name="product",
            name="productID",
            field=models.UUIDField(
                default=uuid.UUID("363f37b7-1a4f-4a1c-83ca-73818348ae8b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="altText",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Image Name"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="imageURL",
            field=models.ImageField(
                blank=True,
                upload_to=products.models.product_image_path,
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="quantityInStock",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="size",
            name="label",
            field=models.CharField(max_length=1, verbose_name="Size Label"),
        ),
        migrations.AlterField(
            model_name="size",
            name="sizeName",
            field=models.CharField(
                default="small", max_length=100, verbose_name="Size Title"
            ),
        ),
    ]
