# Generated by Django 4.1.6 on 2023-02-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productsize_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productsizes",
                to="products.product",
            ),
        ),
    ]
